#!/bin/bash
#install to cgi-bin for httpd /usr/local/cgi-bin/web80/
#ptaffs April 2014. wrir.org 97.3lpfm RVA

sDB=$(ls /var/www/data/*.lsdb|tail -1)

sFirst=0
echo "Content-type: application/json"
echo "Access-Control-Allow-Origin: *"
echo
echo "{\"tracks\": ["

sDBN=${sDB##*/}
sDB2=${sDBN%.lsdb}

sort -k2,3 -t'|' $sDB |
while IFS=\| read sID sArt sTrk sTtl sSet sFol sFil
do
  [[ ${sFirst} = 1 ]] && echo ","
  sFirst=1
  echo "{\"Artist\": \"${sArt}\","
  echo "\"TrackNo\": \"${sTrk}\","
  echo "\"Title\": \"${sTtl}\","
  echo "\"Set\": \"${sSet}\","
  echo "\"Folder\": \"${sFol}\","
  echo "\"sDBver\": \"${sDB2}\","
  echo "\"sTkid\": \"${sID}\"}"
done
echo "]}"
