#!/bin/bash

sMediaPath=/var/www/web1/storage/ShowArchive/
sFirst=0
#echo "Content-type: text/json"
echo "Content-type: application/javascript"
echo
echo "var aoShows={\"shows\": ["
find ${sMediaPath}/*.ready -mtime -14|sort -r|
while read sFile
do
  [[ ${sFirst} = 1 ]] && echo ","
  sFirst=1
  
  sBaseName=${sFile##*/}
  sShow=${sBaseName:13:99}
  sShow=${sShow%%.ready}

  if [[ -f ${sFile%%.ready}.info ]]; then
    sInfo=$(<${sFile%%.ready}.info)
    IFS='|' read sF1 sDa sShow sDJ sSD <<< "${sInfo}"
  else
    unset sF1 sDa sDJ sSD
  fi

  if [[ -f ${sFile%%.ready}.audio.txt ]]; then
    IFS='|' read sTag sDurs < ${sFile%%.ready}.audio.txt
  else
    unset sDurs
  fi
 
  sData=$(grep "|${sShow}|" ${sMediaPath}/showdata.txt|head -1)
  [[ -z "${sData}" ]]  && sData="||${sShow}|${sShow}||||||||"
  sPrinTime=$(date -d "${sBaseName:0:4}/${sBaseName:4:2}/${sBaseName:6:2} ${sBaseName:8:2}:${sBaseName:10:2}"  +"%a %d %_I:%M %P")
  sUXTime=$(date -d "${sBaseName:0:4}/${sBaseName:4:2}/${sBaseName:6:2} ${sBaseName:8:2}:${sBaseName:10:2}")

  IFS='|' read -a sShowData <<< "${sData}"
  
  echo "{\"title\": \"${sShowData[3]}\","
  echo "\"show\": \"${sSD}\","
  echo "\"presenter\": \"${sShowData[5]}\","
  echo "\"presenter2\": \"${sDJ}\","
  echo "\"datestamp\": \"${sBaseName:0:12}\","
  echo "\"dateinfo\": \"${sPrinTime}\","
  echo "\"dateunix\": \"${sUXTime}\","
  echo "\"mp3\": \"http://files.wrir.org/shows/${sBaseName%%.ready}.mp3\","
  echo "\"oga\": \"http://files.wrir.org/shows/${sBaseName%%.ready}.ogg\","
  echo "\"type\": \"${sShowData[4]}\","
  echo "\"duration\": \"${sDurs}\","
  echo "\"poster\": \"${sShowData[7]}\","
  echo "\"showurl\": \"${sShowData[6]}\"}"
done
echo "]};"

sSched="${sMediaPath}/showdata.txt"

sDay=$(date "+%A")
sNow=$(date "+%H%M")

sDone=N

echo

#the script needs a midnight, else won't report on last entry
sMidnight=/tmp/fakeend.$$
echo "${sDay}|2400|Midnight||||||" > ${sMidnight}

grep "^${sDay}|" ${sSched} | cat - ${sMidnight} |
while [[ ${sDone} = N ]] && read sLine
do
  IFS='|' read -a sShowData <<< "${sLine}"
  if [[ 10#${sNow} -ge 10#${sShowData[1]} ]]
  then 
    sMatch=("${sShowData[@]}")
  else
    echo "var oOnNow={\"title\": \"${sMatch[3]}\","
    echo "\"presenter\": \"${sMatch[5]}\","
    echo "\"start\": \"${sMatch[1]}\","
    echo "\"now\": \"${sNow}\","
    echo "\"end\": \"${sShowData[1]}\","
    echo "\"type\": \"${sMatch[4]}\","
    echo "\"poster\": \"${sMatch[7]}\","
    echo "\"showurl\": \"${sMatch[6]}\"};"
    sDone=Y
  fi
done 

rm ${sMidnight}
